<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>cc88afa6-21c7-4963-ae6f-61ae42ce8576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-giftcards</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search-giftcards']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17120533-d32f-4b76-b0d3-679925b2c56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09e4de28-4d44-4b58-8b3d-0e7ea2903f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-giftcards</value>
      <webElementGuid>f64e68f6-378c-40de-ae61-a3f54dcb014c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-search</value>
      <webElementGuid>73a4e436-ba62-4a5a-94c5-7fdc821a6911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Search
</value>
      <webElementGuid>9ec9b39f-83e5-45f4-a81c-60db218869d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-giftcards&quot;)</value>
      <webElementGuid>d2b940a3-493f-4796-8ac2-2ec2947a4368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='search-giftcards']</value>
      <webElementGuid>e5a4e9f3-aa50-4dcc-85d2-2d3934310d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gift card coupon code'])[1]/following::button[1]</value>
      <webElementGuid>92342ea8-c3c5-4ce8-a9ef-c23610921f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activated'])[1]/following::button[1]</value>
      <webElementGuid>2b8ec672-5a99-49ac-9bc7-7cbc7a3862d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gift cards'])[1]/preceding::button[1]</value>
      <webElementGuid>b482519f-a099-4e77-a54c-741143b3839c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>f64328f2-59a2-477e-ae96-7144f778c375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'search-giftcards' and (text() = '

Search
' or . = '

Search
')]</value>
      <webElementGuid>b2983af3-7afd-4552-bfe9-03564e93d69e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
