<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Today_LcoLfSxp</name>
   <tag></tag>
   <elementGuidId>cc90ad80-0a17-4ade-b2a0-6598bb1d13d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='LcoLfSxp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LcoLfSxp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>c5d04eb7-1fa7-4632-8ba0-acf849d8a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LcoLfSxp</value>
      <webElementGuid>37708f0b-fa4f-41d4-949c-e1815299369a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>274</value>
      <webElementGuid>03fd5839-7980-4690-99ab-080019cff155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>265</value>
      <webElementGuid>26cc6f67-a655-4810-93ad-9188cd787bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LcoLfSxp&quot;)</value>
      <webElementGuid>0b33c823-3fe4-4b96-b55c-339c2f49ec33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='LcoLfSxp']</value>
      <webElementGuid>9a51ec6c-5c74-4b92-9bdc-eb1568670ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[6]/div/div[2]/div/div/canvas</value>
      <webElementGuid>34d94aba-0d03-4c02-9955-1e5c229554a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/canvas</value>
      <webElementGuid>43674e69-d6b3-4ddf-b7f4-19cb18080273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'LcoLfSxp']</value>
      <webElementGuid>ef261a24-72d6-406a-975a-0f3bc717a8b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
