<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jeane</name>
   <tag></tag>
   <elementGuidId>b9306ab0-5fd8-4378-a867-7f81a6f4a39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='GreesellaAdhalia'])[1]/following::a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d977ce45-1d89-4081-8bbd-f50d530117ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/member/detail/id/272?lang=id</value>
      <webElementGuid>3cb0c142-72f1-46ff-8067-63ede13acaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JeaneVictoria</value>
      <webElementGuid>1c17a563-0fbb-469e-9900-94db5451c748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 order-1 order-lg-2 entry-contents__main-area&quot;]/div[@class=&quot;row row-all-10&quot;]/div[@class=&quot;col-4 col-lg-2&quot;]/div[@class=&quot;entry-member&quot;]/p[@class=&quot;entry-member__name&quot;]/a[1]</value>
      <webElementGuid>40a30d50-d115-47e4-8616-322b3681f6a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GreesellaAdhalia'])[1]/following::a[2]</value>
      <webElementGuid>40a9ffbe-3e3e-4b88-b711-d629244fa1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GraceOctaviani'])[1]/following::a[4]</value>
      <webElementGuid>571385f2-5f36-4977-87e8-012fe964857d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MichelleAlexandra'])[1]/preceding::a[2]</value>
      <webElementGuid>84f4a7bb-bf12-4730-b72d-6b47de102551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Fan Letter dan Hadiah >'])[1]/preceding::a[3]</value>
      <webElementGuid>9d0267c0-9170-4550-8445-fcb3ad4731a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jeane']/parent::*</value>
      <webElementGuid>9b07723e-9409-42f4-a2eb-673edff97e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/member/detail/id/272?lang=id')])[2]</value>
      <webElementGuid>246d6d1a-2e71-4178-9590-65231fdf2608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[12]/div/p/a</value>
      <webElementGuid>1e512351-bbff-45d8-a0a8-1a8743f4c08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/member/detail/id/272?lang=id' and (text() = 'JeaneVictoria' or . = 'JeaneVictoria')]</value>
      <webElementGuid>d33f25fc-6817-42e1-8287-bb515d9baf1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
