<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_JeaneVictoria</name>
   <tag></tag>
   <elementGuidId>deb0708b-5e70-4383-a238-18465601443a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='GreesellaAdhalia'])[1]/following::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>10ac14e4-e29b-4d40-9f09-95c61db50827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry-member__name</value>
      <webElementGuid>f01a8959-1e0b-4c73-b805-a045232cc59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JeaneVictoria</value>
      <webElementGuid>cdf6920d-8e56-4455-8875-35a86cb1b707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 order-1 order-lg-2 entry-contents__main-area&quot;]/div[@class=&quot;row row-all-10&quot;]/div[@class=&quot;col-4 col-lg-2&quot;]/div[@class=&quot;entry-member&quot;]/p[@class=&quot;entry-member__name&quot;]</value>
      <webElementGuid>e644fe15-c0ba-4531-97e1-e2dd912e1a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GreesellaAdhalia'])[1]/following::p[1]</value>
      <webElementGuid>ba174021-505f-491a-8fdb-e08c964f4468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GraceOctaviani'])[1]/following::p[2]</value>
      <webElementGuid>1ef678d8-10c1-43c2-bc12-6c54a1f5ce24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MichelleAlexandra'])[1]/preceding::p[1]</value>
      <webElementGuid>cf8bdd9b-1a34-436f-85a8-1bd97dca6cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[12]/div/p</value>
      <webElementGuid>930cc231-6a2b-412e-a991-e37a5f8a874b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'JeaneVictoria' or . = 'JeaneVictoria')]</value>
      <webElementGuid>e2cc75b8-2e0c-4873-a629-ac27537db143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
